name: Packaged Development Edition

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: |
            pip install -r requirements.txt
        
      - name: Run build script
        run: |
          python lib/pre-commit.py -t dev
          python lib/build.py pack
      - name: Archive Main build
        uses: actions/upload-artifact@v2
        with:
          name: HoYoGameLauncher.zip
          path: HoYoGameLauncher/
